name: contact-deploy

on:
  push:
    branches: ['main']
    paths:
      - 'src/**'
jobs:
  trigger-pipeline:
    name: Start contact pipeline
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Trigger contact pipeline
        run: aws codepipeline start-pipeline-execution --name ${{ vars.AWS_CONTACT_PIPELINE_NAME }}